FROM node:22-alpine

# خطوة أساسية لتجميع أي مكتبات أصلية زي bcrypt وموجودة في الـ Alpine
RUN apk add --no-cache python3 make g++

WORKDIR /app

# 1. انسخ ملفات التثبيت وإعدادات الـ Workspace الأساسية
COPY package.json package-lock.json tsconfig*.json nx.json ./

# 2. خطوة جوهرية: انسخ مكاتب الـ libs كاملة أولاً عشان الـ npm يربطها بالـ Workspaces
COPY libs/ ./libs/

# 3. دلوقتي ثبت الـ Packages (الـ npm هيعمل Symlinks للـ common و core و security بنجاح)
RUN npm ci

# 4. انسخ باقي مراجع الـ Workspace والـ Apps
COPY . .


RUN npx prisma generate --schema=apps/user-service/prisma/schema.prisma

RUN npx nx build user-service


# EXPOSE 3001
# CMD ["node", "apps/user-service/dist/main.js"]

RUN chmod +x apps/user-service/start.sh

EXPOSE 3001

CMD ["sh", "apps/user-service/start.sh"]

